In [3]:
import numpy as np

In [4]:
a = np.array([1,3,3], dtype=np.int32)
a.dtype

dtype('int32')

In [7]:
b=np.array([1,2,3], dtype=np.float)
b.dtype

dtype('float64')

In [8]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [14]:
d = np.array([[1,2,3],[4,5,6]])
d

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
# 生成2行3列全为0的矩阵
zero = np.zeros((2,3))
zero

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
# 生成3行4列全为1的矩阵
one = np.ones((3,4))
one

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
# 生成3行2列全都接近于0（不等于0）矩阵
empty = np.empty((3,2))
empty

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [21]:
e = np.arange(10)
e

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
f = np.arange(4, 12)
f

array([ 4,  5,  6,  7,  8,  9, 10, 11])

In [25]:
g = np.arange(1, 20, 3)
g

array([ 1,  4,  7, 10, 13, 16, 19])

In [28]:
# arange 从0 到 8（不含8）
# reshape 生成2行4列
h = np.arange(8).reshape(2, 4)
h

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])