In [1]:
import numpy as np

In [8]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[1,1,2], [2,3,3]])
arr1
arr2

array([[1, 1, 2],
       [2, 3, 3]])

In [10]:
arr1 + arr2

array([[2, 3, 5],
       [6, 8, 9]])

In [11]:
arr1 - arr2

array([[0, 1, 1],
       [2, 2, 3]])

In [12]:
arr1 * arr2

array([[ 1,  2,  6],
       [ 8, 15, 18]])

In [13]:
arr1 ** arr2

array([[  1,   2,   9],
       [ 16, 125, 216]])

In [15]:
arr1 / arr2

array([[1.        , 2.        , 1.5       ],
       [2.        , 1.66666667, 2.        ]])

In [17]:
# 取余
arr1 % arr2

array([[0, 0, 1],
       [0, 2, 0]])

In [19]:
arr1 // arr2  # 取整

array([[1, 2, 1],
       [2, 1, 2]])

In [21]:
# 所有的元素都地加2
arr1 + 2

array([[3, 4, 5],
       [6, 7, 8]])

In [22]:
# 所有元素都乘以10
arr1 * 10

array([[10, 20, 30],
       [40, 50, 60]])

In [24]:
# 判断哪些元互大于3
arr3 = arr1 > 3
arr3

array([[False, False, False],
       [ True,  True,  True]])

In [25]:
# 生成3行5列的矩阵
arr4 = np.ones((3,4))
arr4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
print(arr1)
print(arr4)

[[1 2 3]
 [4 5 6]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [27]:
# 矩阵乘法1
np.dot(arr1, arr4)

array([[ 6.,  6.,  6.,  6.],
       [15., 15., 15., 15.]])

In [31]:
# 矩阵乘法2
arr1.dot(arr4)

array([[ 6.,  6.,  6.,  6.],
       [15., 15., 15., 15.]])

In [32]:
print(arr1)
print(arr1.T) # 矩阵转置
print(np.transpose(arr1))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]
