In [ ]:
import numpy as np

In [ ]:
# 生成3行2列从0到1的随机数
sample1 = np.random.random((3,2))
sample1

In [ ]:
# 生成3行2列符合标准正态分布的随机数
sample2 = np.random.normal(size=(3,2))
sample2

In [ ]:
sample3 = np.random.randint(0, 10, size=(3,2))
sample3

In [ ]:
np.sum(sample1)

In [ ]:
# 提取最小值
np.min(sample1)

In [ ]:
# 提取最大值
np.max(sample1)

In [ ]:
# 对列求和
np.sum(sample1, axis=0)

In [ ]:
# 对行求和
np.sum(sample1, axis=1)

In [29]:
sample1

array([[0.57058028, 0.4166554 ],
       [0.83078472, 0.78530579],
       [0.79608785, 0.68102867]])

In [ ]:
# 取最小值的索引
np.argmin(sample1)

In [ ]:
# 取最大值的索引
np.argmax(sample1)

In [ ]:
# 所有元素的平均值 
np.mean(sample1)

In [ ]:
# 所有元素的平均值
sample1.mean()

In [30]:
# 求中位, 如果是奇数个值 ，就取中间的值 ； 如果是偶数个值， 就取中间丙个
np.median(sample1)


0.7331672335432726

In [31]:
# 开方
np.sqrt(sample1)

array([[0.75536765, 0.6454885 ],
       [0.91147393, 0.88617481],
       [0.89223755, 0.82524461]])

In [33]:
sample4 = np.random.randint(0,10, size=(1, 10))
sample4

array([[8, 8, 7, 0, 6, 9, 5, 3, 8, 2]])

In [34]:
np.sort(sample4)

array([[0, 2, 3, 5, 6, 7, 8, 8, 8, 9]])

In [36]:
np.sort(sample1)

array([[0.4166554 , 0.57058028],
       [0.78530579, 0.83078472],
       [0.68102867, 0.79608785]])

In [ ]:
# 元素小2的变成2， 大于7的变成7，中间的不变
np.clip(sqmple4, 2, 7)