In [2]:
import numpy as np

In [3]:
arr1 = np.arange(2, 14)
arr1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [4]:
arr1[2]

4

In [5]:
# 第一到第四个位置的数据
arr1[1:4]

array([3, 4, 5])

In [6]:
# 前五个数据
arr1[:5]

array([2, 3, 4, 5, 6])

In [7]:
# 最后两个数据
arr1[-2:]

array([12, 13])

In [8]:
arr2 = arr1.reshape(3, 4)
arr2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [9]:
# 第一行， 第二列
arr2[1, 2]

8

In [10]:
# 所有行的第2列
arr2[:,2]

array([ 4,  8, 12])

In [12]:
for i in arr2:
    print(i)
    

[2 3 4 5]
[6 7 8 9]
[10 11 12 13]


In [13]:
# 使用转置， 可以迭代列
for i in arr2.T:
    print(i)

[ 2  6 10]
[ 3  7 11]
[ 4  8 12]
[ 5  9 13]


In [14]:
# 迭代元素
for i in arr2.flat:
    print(i)

2
3
4
5
6
7
8
9
10
11
12
13
