In [1]:
import numpy as np

In [4]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
# 垂直合并
arr3 =  np.vstack((arr1, arr2))
print(arr3)
arr3.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [6]:
# 水平合并
arr4 = np.hstack((arr1, arr2))
print(arr4)
arr4.shape

[1 2 3 4 5 6]


(6,)

In [7]:
arr5 = np.vstack((arr1, arr2, arr3))
arr5

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [8]:
arr6 = np.hstack((arr1, arr2, arr4))
arr6

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

In [9]:
arr = np.concatenate((arr1, arr2, arr1));
arr

array([1, 2, 3, 4, 5, 6, 1, 2, 3])

In [11]:
# axis=0 垂直合并， axis=1 水平合并
# 注意： 合并的array维度要相同， 形状要匹配
arr = np.concatenate((arr3, arr5), axis=0)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [12]:
# 维度要相同， 形状要匹配， axis=1 横向合并
arr = np.concatenate((arr3, arr3), axis=1)
arr

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [13]:
# 一维数组不能转置
arr1.T

array([1, 2, 3])

In [14]:
arr1.shape

(3,)

In [17]:
arr1_1 = arr1[np.newaxis,:]
print(arr1_1)
arr1_1.shape

[[1 2 3]]


(1, 3)

In [18]:
# 至少是2维数组， 如果不是就转成2维
arr1_3 = np.atleast_2d(arr1)
print(arr1_3)
arr1_3.T

[[1 2 3]]


array([[1],
       [2],
       [3]])