In [1]:
import numpy as np

In [2]:
arr1 = np.arange(12).reshape((3,4))
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
# 垂直方向切成两份
arr2, arr3 = np.split(arr1,2,axis=1)
print(arr2)
print('----------')
print(arr3)

[[0 1]
 [4 5]
 [8 9]]
----------
[[ 2  3]
 [ 6  7]
 [10 11]]


In [8]:
# 水平方向分割， 分成3份
arr4, arr5,arr6 = np.split(arr1,3,axis=0)
print(arr4)
print('-------')
print(arr5)
print('-------')
print(arr5)

[[0 1 2 3]]
-------
[[4 5 6 7]]
-------
[[4 5 6 7]]


In [12]:
# 不等分的时候，也不报错
arr7, arr8, arr9 = np.array_split(arr1,3,axis=1)
print(arr7)
print('-------')
print(arr8)
print('-------')
print(arr9)

[[0 1]
 [4 5]
 [8 9]]
-------
[[ 2]
 [ 6]
 [10]]
-------
[[ 3]
 [ 7]
 [11]]


In [13]:
# 水平分割 
arr10, arr11, arr12 = np.vsplit(arr1, 3)
print(arr10)
print(arr11)
print(arr12)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]


In [14]:
# 垂直分割
arr13, arr14 = np.hsplit(arr1,  2)
print(arr13)
print('-------')
print(arr14)

[[0 1]
 [4 5]
 [8 9]]
-------
[[ 2  3]
 [ 6  7]
 [10 11]]
