In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3])

In [3]:
arr2 = arr1

In [4]:
arr2[0] = 5
print(arr1)
print(arr2)

[5 2 3]
[5 2 3]


In [5]:
# 深拷贝
arr3 = arr1.copy()

In [6]:
arr3[0] = 10
print(arr1)
print(arr3)

[5 2 3]
[10  2  3]
